default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check (safe mode)
        entry: bash -c 'cd frontend && npm run lint:check'
        language: system
        types: [ text ]
        files: ^frontend/
        pass_filenames: false

      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check backend/app --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: unsupported
        types: [ python ]
#        files: ^backend/

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: unsupported
        types: [ python ]
