services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-domains-backend
    restart: always
    env_file:
      - .env.stage
    ports:
      - "8001:8001"
    networks:
      - my-domains-net

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/utils/health-check/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}'
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${DOMAIN?Variable not set}/api
    container_name: my-domains-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - my-domains-net

networks:
  my-domains-net:
    driver: bridge
